modLoader="javafml"
loaderVersion="$forgefmlrange"
issueTrackerURL="https://github.com/${github}/issues"
license="$license"
logoFile="pack.png"

[[mods]]
    modId="$id"
    version="$version"
    displayName="$libname"
    displayTest="IGNORE_SERVER_VERSION"
    updateJSONURL="https://forge.curseupdate.com/1029438/watermedia-binaries"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia-binaries"
    credits="$credits"
    authors="$authors"
    logoFile="pack.png"
    description='''$description'''

[[dependencies.$id]]
    modId="watermedia"
    mandatory=true
    versionRange="[$watermediaversion,)"
    ordering="NONE"
    side="CLIENT"